<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2018.1.0.386
*/


// require_once('phpmailer/PHPMailerAutoload.php');
// $mail = new PHPMailer;
// $mail->CharSet = 'utf-8';

// $phone = $_POST['user_phone'];

// //$mail->SMTPDebug = 3;									// Enable verbose debug output

// $mail->isSMTP();										// Set mailer to use SMTP
// $mail->Host = 'smtp.mail.ru';							// Specify main and backup SMTP servers
// $mail->SMTPAuth = true;									// Enable SMTP authentication
// $mail->Username = 'aleks.kuzneczov.90@mail.ru';			// Ваш логин от почты с которой будут отправляться письма
// $mail->Password = '41691871xand90';						// Ваш пароль от почты с которой будут отправляться письма
// $mail->SMTPSecure = 'ssl';								// Enable TLS encryption, `ssl` also accepted
// $mail->Port = 465;										// TCP port to connect to / этот порт может отличаться у других провайдеров

// $mail->setFrom('aleks.kuzneczov.90@mail.ru');			// от кого будет уходить письмо?
// $mail->addAddress('lid.konversia@yandex.ru');			// Кому будет уходить письмо 
// //$mail->addAddress('ellen@example.com');				// Name is optional
// //$mail->addReplyTo('info@example.com', 'Information');
// //$mail->addCC('cc@example.com');
// //$mail->addBCC('bcc@example.com');
// //$mail->addAttachment('/var/tmp/file.tar.gz');			// Add attachments
// //$mail->addAttachment('/tmp/image.jpg', 'new.jpg');	// Optional name
// $mail->isHTML(true);									// Set email format to HTML

// $mail->Subject = 'Заявка с тестового сайта';
// $mail->Body    = ' телефон ' .$phone;
// $mail->AltBody = '';

// if(!$mail->send()) {
//     echo 'Error';
// } else {
//     header('location: ../thank-you.html');
// }

if ($_POST['phone'] && $_POST['email']) {

    $headers = 'From: Brandon\r\n' .
        'Reply-To: lid.konversia@yandex.ru\r\n' .
        'X-Mailer: PHP/' . phpversion();

    $theme = 'Новое сообщение';
    $letter .= 'Номер телефона: ' . $_POST['phone'] . '\r\n';
	$letter .= 'Email: ' . $_POST['email'] . '\r\n';

    if (mail('lid.konversia@yandex.ru', $theme, $letter, $headers)) {
        header('location:/');
    }
}

?>
